language: python
python:
- 3.6
install: pip install -r requirements_dev.txt
script: py.test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bobtiki
  password:
    secure: cOKAMX/66YxZ/CVnC+f8u2IuKkMZWYX0nQSzyVUlv44MpppsiypbYtLJ3SY3aK1ydyix4NgKpqMqDwFk0qxOBB5RF5Nlw98nYgK/QhZJLj8wgBEaNhyk/ONw1mgzcDv+a3TSf1iF+t9WzxNNQjM9eORu0qdi4fyNKINCmxtsThLKhCSiC1PGpGwvb1f3RMEdyeJQ2ZCAMrXNiYldHpp6LfsxKPD77yEBVIn8/wbjw16/sonZcfxR6Tpri56fN6AUxL+Reu5FErZzcIpFAlhKgnQ64YOYOb6YH4b47luOj2iUe9loveHElsNt0sYYekGJWox7qScd7bZl5SCR1XDUDY+LCVvZzsiRsNk/bQPb4wv/zAtFDLFE/lZjPNZqr2Hn2B5/dVDhLw5+2UYfZl5GC/y3gizVhzMfdRgNAVso4ZRmMsKtlrouLVPvigS5yvPtQNyM34/jlprEMnYgGoBC9h08TYR133d/4g5M1GkzecbDEY/hg+9FaNy/s1No3AU8/PwtQWnz/4nL1yizyQz6niPC3L3n9IrC0m1y8OWeS8gmoaRfTQUwRgoCYXKWaTLs056hvI3smCLfceBnvYMQnWvAGH7n1CeLxblvnsPIZeScql5ivkfdF+MB9KB3VjorsF4BiP/3KtpR5tjo4U6o+oK78olNvAdshb5mUdiK5Sc=
  on:
    tags: true
    repo: bobtiki/letterboxd
    python: 3.6
